NUMPY  

In [4]:
## numpy is a fundamental library

import numpy as np

## create array using numpy
#create a 1D array

arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row 5 coloumn


array([[1, 2, 3, 4, 5]])

In [6]:
##2D array


arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: ",arr)
print("Shape: ",arr.shape)
print("dimenssions : ",arr.ndim)
print("no of elements:",arr.size)
print("Data type",arr.dtype)


Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
dimenssions :  2
no of elements: 9
Data type int64


In [ ]:
### Numpy VEctorized Operation

arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,20,30,40,50,60])


## elemnt wise addition

print("addition: ",arr1+arr2)

##element wise subtraction
print("subtraction: ",arr2-arr1)

arr=np.array([2,3,4,5,6])

###square root
print(np.sqrt(arr))






addition:  [11 22 33 44 55 66]
subtraction:  [ 9 18 27 36 45 54]
[1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [8]:
### array slicing and indexing

arr=np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]])
print("Array : \n",arr)


Array : 
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
val=arr[0][3]
print(val)

4


In [10]:
arr[0,0]=100
print(arr)

[[100   2   3   4   5]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [11]:
#### statistical concepts -- Normalization
### to have a mean of 0 and standard deviation 


data=np.array([1,2,4,5,6])
mean=np.mean(data)
std_dev=np.std(data)

# normalize the data
normalized_data=(data-mean)/std_dev
print(normalized_data)

[-1.40182605 -0.86266219  0.21566555  0.75482941  1.29399328]
